notifications:
    email:
        on_success: change
        on_failure: change

language: python


env:
    global:
        - POSTGRES_USER="postgres"
        - MYSQL_USER="root"
    matrix:
        - SRP_PYTHON="py27"    SRP_DB="sqlite"
        - SRP_PYTHON="py27"    SRP_DB="psycopg2"
        - SRP_PYTHON="py27"    SRP_DB="pymysql"
        - SRP_PYTHON="py35"    SRP_DB="sqlite"
        - SRP_PYTHON="py35"    SRP_DB="psycopg2"
        - SRP_PYTHON="py35"    SRP_DB="pymysql"

matrix:
    include:
        - env: SRP_PYTHON="py33"    SRP_DB="sqlite"
        - env: SRP_PYTHON="py34"    SRP_DB="sqlite"
        - env: SRP_PYTHON="py27"    SRP_DB="mysqldb"
        - env: SRP_PYTHON="pypy"    SRP_DB="sqlite"
        - env: SRP_PYTHON="pypy3"   SRP_DB="sqlite"
        - env: TEST_SUITE="javascript"
    allow_failures:
        - env: SRP_PYTHON="pypy" SRP_DB="sqlite"
        - env: SRP_PYTHON="pypy3" SRP_DB="sqlite"
    fast_finish: true

before_install: make travis-setup

install:
    - nvm install 5.3.0
    - npm install -g npm@latest
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.8 graphviz
    - export CXX=g++-4.8
    - make build-deps

before_script: make all

script: make travis

after_success: make travis-success
