addons:
# Use MariaDB instead of MySQL for for better defaults and better reflection of
# what is actually being used.
    mariadb: '10.0'
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
# See below why g++4.8 is required, graphviz is required for building the docs.
        - g++-4.8
        - graphviz

cache:
  pip: true
  directories:
    - node_modules

services:
    - postgresql

# sudo: false means we use the container-based infrastructure. Bit faster, and
# we get caching for free.
sudo: false

notifications:
    email:
        on_success: change
        on_failure: change

language: python

env:
    global:
        - POSTGRES_USER="postgres"
        - MYSQL_USER="root"

matrix:
    include:
# Standard support
        - env: SRP_PYTHON="py27"    SRP_DB="sqlite"
          python: 2.7
        - env: SRP_PYTHON="py27"    SRP_DB="psycopg2"
          python: 2.7
        - env: SRP_PYTHON="py27"    SRP_DB="pymysql"
          python: 2.7
        - env: SRP_PYTHON="py36"    SRP_DB="sqlite"
          python: 3.6
        - env: SRP_PYTHON="py36"    SRP_DB="psycopg2"
          python: 3.6
        - env: SRP_PYTHON="py36"    SRP_DB="pymysql"
          python: 3.6
# Extra support
        - env: SRP_PYTHON="py34"    SRP_DB="sqlite"
          python: 3.4
        - env: SRP_PYTHON="py35"    SRP_DB="sqlite"
          python: 3.5
        - env: SRP_PYTHON="py27"    SRP_DB="mysqldb"
          python: 2.7
        - env: SRP_PYTHON="pypy"    SRP_DB="sqlite"
          python: pypy
# Disable PyPy3 until it supports Python 3.3
#       - env: SRP_PYTHON="pypy3"   SRP_DB="sqlite"
# Special test suites
        - env: TEST_SUITE="javascript"
        - env: TEST_SUITE="docs"
    allow_failures:
# Pypy is weird and takes a long time to test
        - env: SRP_PYTHON="pypy"    SRP_DB="sqlite"
          python: pypy
# See above note on PyPy3
#       - env: SRP_PYTHON="pypy3"   SRP_DB="sqlite"
    fast_finish: true

before_install:
# Update to a recent version of Node, npm and pip
    - nvm install 8.6.0
    - npm install -g npm@latest
    - npm install
    - pip install --upgrade pip
    - make travis-setup

install:
# One of the Node modules (microtime, required by selectize) needs g++ >=4.8
    - export CXX=g++-4.8
    - make build-deps

script: TOXENV="$SRP_PYTHON-$SRP_DB" make travis

after_success: make travis-success

before_cache:
# Remove our files from the caches
    - rm -f node_modules/evesrp
    - find ~/.cache/pip -name 'EVE_SRP*' -delete
