addons:
    mariadb: '10.0'
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
        - graphviz

cache:
  pip: true
  directories:
    - node_modules

services:
    - postgresql

sudo: false

notifications:
    email:
        on_success: change
        on_failure: change

language: python

env:
    global:
        - POSTGRES_USER="postgres"
        - MYSQL_USER="root"

matrix:
    include:
# Standard support
        - env: SRP_PYTHON="py27"    SRP_DB="sqlite"
        - env: SRP_PYTHON="py27"    SRP_DB="psycopg2"
        - env: SRP_PYTHON="py27"    SRP_DB="pymysql"
# Python 3.5 is required to be set explicitly, unlike other versions of Python 3
        - env: SRP_PYTHON="py35"    SRP_DB="sqlite"
          python: 3.5
        - env: SRP_PYTHON="py35"    SRP_DB="psycopg2"
          python: 3.5
        - env: SRP_PYTHON="py35"    SRP_DB="pymysql"
          python: 3.5
# Extra support
        - env: SRP_PYTHON="py33"    SRP_DB="sqlite"
        - env: SRP_PYTHON="py34"    SRP_DB="sqlite"
        - env: SRP_PYTHON="py27"    SRP_DB="mysqldb"
        - env: SRP_PYTHON="pypy"    SRP_DB="sqlite"
        - env: SRP_PYTHON="pypy3"   SRP_DB="sqlite"
# Special test suites
        - env: TEST_SUITE="javascript"
        - env: TEST_SUITE="docs"
    allow_failures:
# Pypy is weird and takes a long time to test
        - env: SRP_PYTHON="pypy" SRP_DB="sqlite"
        - env: SRP_PYTHON="pypy3" SRP_DB="sqlite"
    fast_finish: true

before_install:
    - nvm install 5.3.0
    - npm install -g npm@latest
    - npm install
    - make travis-setup

install:
    - export CXX=g++-4.8
    - make build-deps

script: TOXENV="$SRP_PYTHON-$SRP_DB" make travis

after_success: make travis-success

before_cache:
    - rm -f node_modules/evesrp
    - find ~/.cache/pip -name 'EVE_SRP*' -delete
